const oreImages = {
    "Pumpkinite": "../src/Pumpkinite.png",
    "Sinistyte L": "../src/Sinistyte L.png",
    "Sinistyte M": "../src/Sinistyte M.png",
    "Sinistyte S": "../src/Sinistyte S.png",
    "Sinistyte E": "../src/Sinistyte E.png",
    "Nightmarium": "../src/Nightmarium.png",
    "Twitchite": "../src/Twitchite.png",
    "Frostarium": "../src/Frostarium.png",
    "Giftium": "../src/Giftium.png",
    "Frawstbyte": "../src/Frawstbyte.png",
    "Gingerbreadium": "../src/Gingerbreadium.png",
    "Peppermintium": "../src/Peppermintium.png",
    "Noobite": "../src/Noobite.png",
    "Garnet": "../src/Garnet.png",
    "Moonstone": "../src/Moonstone.png",
    "Kappa": "../src/Kappa.png",
    "Tungsten": "../src/Tungsten.png",
    "Titanium": "../src/Titanium.png",
    "Element V": "../src/Element V.png",
    "Havium": "../src/Havium.png",
    "Valhalum": "../src/Valhalum.png",
    "Nihilium": "../src/Nihilium.png",
    "Ambrosia": "../src/Ambrosia.png",
    "Stone": "../src/Stone.png",
    "Coal": "../src/Coal.png",
    "Iron": "../src/Iron.png",
    "Gold": "../src/Gold.png",
    "Copper": "../src/Copper.png",
    "Silver": "../src/Silver.png",
    "Topaz": "../src/Topaz.png",
    "Sulfur": "../src/Sulfur.png",
    "Sapphire": "../src/Sapphire.png",
    "Ruby": "../src/Ruby.png",
    "Emerald": "../src/Emerald.png",
    "Diamond": "../src/Diamond.png",
    "Opal": "../src/Opal.png",
    "Boomite": "../src/Boomite.png",
    "Uranium": "../src/Uranium.png",
    "Serendibite": "../src/Serendibite.png",
    "Amethyst": "../src/Amethyst.png",
    "Platinum": "../src/Platinum.png",
    "Shadow Metal": "../src/Shadow Metal.png",
    "Illuminunium": "../src/Illuminunium.png",
    "Plutonium": "../src/Plutonium.png",
    "Baryte": "../src/Baryte.png",
    "Rainbonite": "../src/Rainbonite.png",
    "Orichalcum": "../src/Orichalcum.png",
    "Alexandrite": "../src/Alexandrite.png",
    "Azure": "../src/Azure.png",
    "Mithril": "../src/Mithril.png",
    "Nullstone": "../src/Nullstone.png",
    "Dragonglass": "../src/Dragonglass.png",
    "Painite": "../src/Painite.png",
    "Soulstone": "../src/Soulstone.png",
    "Firecrystal": "../src/Firecrystal.png",
    "Symmetrium": "../src/Symmetrium.png",
    "Dragonstone": "../src/Dragonstone.png",
    "Promethium": "../src/Promethium.png",
    "Newtonium": "../src/Newtonium.png",
    "Corium": "../src/Corium.png",
    "Yunium": "../src/Yunium.png",
    "Solarium": "../src/Solarium.png",
    "Frightstone": "../src/Frightstone.png",
    "Redmatter": "../src/Redmatter.png",
    "Darkmatter": "../src/Darkmatter.png",
    "Antimatter": "../src/Antimatter.png",
    "Stellarite": "../src/Stellarite.png",
    "Constellatium": "../src/Constellatium.png",
    "Mightstone": "../src/Mightstone.png"
};

window.oreImages = oreImages;