const oreValues = {
    "Pumpkinite":      { AV: 18 },
    "Sinistyte M":     { AV: 325 },
    "Sinistyte L":     { AV: 250 },
    "Sinistyte S":     { AV: 190 },
    "Sinistyte E":     { AV: 190 },
    "Nightmarium":     { AV: 65 },
    "Twitchite":       { AV: 7 },
    "Frostarium":      { AV: 1250 },
    "Giftium":         { AV: 300 },
    "Frawstbyte":      { AV: 340 },
    "Gingerbreadium":  { AV: 210 },
    "Peppermintium":   { AV: 200 },
    "Noobite":         { AV: 130 },

    "Garnet":          { AV: 150 },
    "Moonstone":       { AV: 130 },
    "Kappa":           { AV: 20 },
    "Tungsten":        { AV: 160 },
    "Titanium":        { AV: 80 },
    "Element V":       { AV: 12 },
    "Havium":          { AV: 9 },
    "Valhalum":        { AV: 9 },
    "Nihilium":        { AV: 12 },
    "Ambrosia":        { AV: 1 },

    "Stone":           { AV: 275000 },
    "Coal":            { AV: 150000 },
    "Iron":            { AV: 30000 },
    "Gold":            { AV: 4000 },
    "Copper":          { AV: 14000 },
    "Silver":          { AV: 125000 },
    "Topaz":           { AV: 2400 },
    "Sulfur":          { AV: 13000 },
    "Sapphire":        { AV: 11500 },
    "Ruby":            { AV: 9000 },
    "Emerald":         { AV: 7000 },
    "Diamond":         { AV: 1400 },
    "Opal":            { AV: 1350 },
    "Boomite":         { AV: 175000 },
    "Uranium":         { AV: 1200 },
    "Serendibite":     { AV: 1100 },

    "Amethyst":        { AV: 650 },
    "Platinum":        { AV: 1100 },
    "Shadow Metal":    { AV: 110 },
    "Illuminunium":    { AV: 70 },

    "Plutonium":       { AV: 800 },
    "Baryte":          { AV: 1000 },
    "Rainbonite":      { AV: 225 },
    "Orichalcum":      { AV: 160 },
    "Alexandrite":     { AV: 215 },
    "Azure":           { AV: 275 },
    "Mithril":         { AV: 90 },

    "Nullstone":       { AV: 1750 },
    "Dragonglass":     { AV: 2250 },
    "Painite":         { AV: 900 },
    "Soulstone":       { AV: 115 },
    "Firecrystal":     { AV: 300 },
    "Symmetrium":      { AV: 65 },

    "Dragonstone":     { AV: 4500 },
    "Promethium":      { AV: 200 },
    "Newtonium":       { AV: 950 },
    "Corium":          { AV: 200 },
    "Yunium":          { AV: 105 },
    "Solarium":        { AV: 90 },

    "Frightstone":     { AV: 1400 },
    "Redmatter":       { AV: 175 },
    "Darkmatter":      { AV: 360 },
    "Antimatter":      { AV: 320 },
    "Stellarite":      { AV: 650 },
    "Constellatium":   { AV: 230 },
    "Mightstone":      { AV: 1100 }
};

window.oreValues = oreValues;   